version: "3.8"
services:
  cache:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - ./tmp/cache:/data

  app:
    build: .
    ports:
      - 3007:3007
    environment:
      REDIS_HOST: cache
      REDIS_PORT: 6379
      PORT: 3007
      CONCURRENT_WORKERS: 1
    volumes:
      - ./:/usr/app
      - /node_modules
      - /dist
      - /tmp
      - /samples/outputs
    depends_on:
      - cache